### ISSUE TITLE
Crash with Forge 57+

### ISSUE THREAD

**Issue by vico93** [Tfarcenim/firesmelting#1]
After updating Forge from 22 to 57 my modpack began to crash when i try to start it.

Testing with each mod i found when i have firesmelting-2.0-1.16.2 in my modpack i get this crash: https://pastebin.com/G110BP64

Without it the modpack loads fine.

I tried to update again Forge to 59 (since folks on MMD server said there were drastic internal changes in Forge and from what understand in the Forge changelog they are trying to fix the stuff) and the crash still happens.

**Comment by Tfarcenim** [comment]
There's nothing I can do about his one as it's a forge/modlauncher issue https://github.com/SpongePowered/Mixin/issues/439

**Comment by vico93** [comment]
Okay. Thanks for the info!
